erase_user:
	rm -f wsp_client.bin
	rm -f /mnt/Data/Escuela/4to/SistDist/client/wsp_client.bin

update:
	cp /mnt/Data/Escuela/4to/SistDist/Proyecto/whatsappP2P/client/*.py /mnt/Data/Escuela/4to/SistDist/client

reset:
	rm -f wsp_client.bin
	rm -f /mnt/Data/Escuela/4to/SistDist/client/wsp_client.bin
	cp /mnt/Data/Escuela/4to/SistDist/Proyecto/whatsappP2P/client/*.py /mnt/Data/Escuela/4to/SistDist/client
